### ISSUE TITLE
Package will not install

### ISSUE THREAD

**Issue by tolusonaike** [core77/concrete5-foundation#2]
Hello,

I am getting an error message when i try and install the package on a v5.7.5.6 site
![screen shot 2016-02-09 at 12 26 19 pm](https://cloud.githubusercontent.com/assets/253270/12926472/2ee18fa8-cf29-11e5-9238-1ad373abee61.png)

Is this for newer versions of concrete5.7 ? Thanks.

**Comment by core77** [comment]
It should be ready for 5.7.x, yes. 

Your package folder has to be <concrete-root>/packages/foundation_sites
